-- ============================================================
-- FinTrack — 03_seed_coa.sql
-- Chart of Accounts. Header (is_header=true) = level 1 & 2, tidak bisa diposting.
-- Leaf (is_header=false, level 3) = postable.
-- Semua is_active=true (DORMANT hanya berarti tidak di-mapping ke menu bot).
-- NB: aset & beban = debit normal; liabilitas, ekuitas, pendapatan = credit normal.
-- ============================================================

INSERT INTO chart_of_accounts
    (code, parent_code, level, account_name, account_type, normal_balance, is_header, notes) VALUES

-- ===== 1000 ASET =====
('1000', NULL,   1, 'ASET',                          'aset', 'debit',  true,  'Header kelas'),
('1100', '1000', 2, 'Kas & Setara Kas',              'aset', 'debit',  true,  'Header kelompok'),
('1110', '1100', 3, 'Kas Tunai',                     'aset', 'debit',  false, 'Aktif — uang tunai di tangan'),
('1120', '1100', 3, 'Bank BNI (Kas Besar)',          'aset', 'debit',  false, 'Aktif — rekening utama, income masuk sini'),
('1130', '1100', 3, 'SeaBank (Kas Kecil Imprest)',   'aset', 'debit',  false, 'Aktif — target Rp 500.000, pengeluaran harian'),
('1140', '1100', 3, 'Bank Tabungan [TBD]',           'aset', 'debit',  false, 'Aktif — ganti nama saat bank dipilih'),
('1150', '1100', 3, 'Kas Kecil Usaha',               'aset', 'debit',  false, 'DORMANT — template bisnis'),
('1200', '1000', 2, 'Investasi JK Pendek',           'aset', 'debit',  true,  'Header'),
('1210', '1200', 3, 'Deposito',                      'aset', 'debit',  false, 'Aktif'),
('1220', '1200', 3, 'Reksa Dana Pasar Uang',         'aset', 'debit',  false, 'Aktif'),
('1230', '1200', 3, 'Reksa Dana Campuran/Saham',     'aset', 'debit',  false, 'Aktif'),
('1240', '1200', 3, 'Saham',                         'aset', 'debit',  false, 'Aktif'),
('1250', '1200', 3, 'SBN / Obligasi Negara',         'aset', 'debit',  false, 'Aktif'),
('1300', '1000', 2, 'Piutang',                       'aset', 'debit',  true,  'Header'),
('1310', '1300', 3, 'Piutang Personal',              'aset', 'debit',  false, 'Aktif'),
('1320', '1300', 3, 'Piutang Usaha',                 'aset', 'debit',  false, 'DORMANT'),
('1330', '1300', 3, 'Uang Muka Pembelian',           'aset', 'debit',  false, 'DORMANT'),
('1390', '1300', 3, 'Cadangan Kerugian Piutang',     'aset', 'credit', false, 'DORMANT — contra asset'),
('1400', '1000', 2, 'Persediaan',                    'aset', 'debit',  true,  'Header'),
('1410', '1400', 3, 'Persediaan Barang Dagang',      'aset', 'debit',  false, 'DORMANT'),
('1420', '1400', 3, 'Bahan Baku & Penolong',         'aset', 'debit',  false, 'DORMANT'),
('1500', '1000', 2, 'Biaya Dibayar Dimuka',          'aset', 'debit',  true,  'Header'),
('1510', '1500', 3, 'Sewa Dibayar Dimuka',           'aset', 'debit',  false, 'Aktif'),
('1520', '1500', 3, 'Asuransi Dibayar Dimuka',       'aset', 'debit',  false, 'DORMANT'),
('1590', '1500', 3, 'Lainnya Dibayar Dimuka',        'aset', 'debit',  false, 'DORMANT'),
('1700', '1000', 2, 'Investasi JK Panjang',          'aset', 'debit',  true,  'Header'),
('1710', '1700', 3, 'Saham Jangka Panjang',          'aset', 'debit',  false, 'Aktif'),
('1720', '1700', 3, 'Emas / Logam Mulia',            'aset', 'debit',  false, 'Aktif'),
('1730', '1700', 3, 'Reksa Dana Jangka Panjang',     'aset', 'debit',  false, 'Aktif'),
('1800', '1000', 2, 'Aset Tetap',                    'aset', 'debit',  true,  'Header'),
('1810', '1800', 3, 'Kendaraan (Motor/Mobil)',       'aset', 'debit',  false, 'Aktif'),
('1820', '1800', 3, 'Peralatan Elektronik (Laptop, HP)', 'aset', 'debit', false, 'Aktif'),
('1830', '1800', 3, 'Perabotan & Perlengkapan',      'aset', 'debit',  false, 'Aktif'),
('1840', '1800', 3, 'Mesin & Peralatan Usaha',       'aset', 'debit',  false, 'DORMANT'),
('1850', '1800', 3, 'Bangunan',                      'aset', 'debit',  false, 'DORMANT'),
('1900', '1000', 2, 'Akumulasi Penyusutan',          'aset', 'credit', true,  'Header — contra asset'),
('1910', '1900', 3, 'Akum. Peny. Kendaraan',         'aset', 'credit', false, 'Saldo=0 personal'),
('1920', '1900', 3, 'Akum. Peny. Peralatan Elektronik','aset','credit', false, 'Saldo=0 personal'),
('1930', '1900', 3, 'Akum. Peny. Perabotan',         'aset', 'credit', false, 'Saldo=0 personal'),

-- ===== 2000 LIABILITAS =====
('2000', NULL,   1, 'LIABILITAS',                    'liabilitas', 'credit', true,  'Header kelas'),
('2100', '2000', 2, 'Utang Jangka Pendek',           'liabilitas', 'credit', true,  'Header'),
('2110', '2100', 3, 'Utang Usaha',                   'liabilitas', 'credit', false, 'DORMANT'),
('2120', '2100', 3, 'Kartu Kredit',                  'liabilitas', 'credit', false, 'Saldo=0, template'),
('2130', '2100', 3, 'SpayLater / Paylater',          'liabilitas', 'credit', false, 'Aktif — saldo=0 saat ini'),
('2140', '2100', 3, 'Utang Personal / Informal',     'liabilitas', 'credit', false, 'Aktif'),
('2200', '2000', 2, 'Biaya Masih Harus Dibayar',     'liabilitas', 'credit', true,  'Header'),
('2210', '2200', 3, 'Utang Gaji',                    'liabilitas', 'credit', false, 'DORMANT'),
('2220', '2200', 3, 'Utang PPN',                     'liabilitas', 'credit', false, 'DORMANT'),
('2400', '2000', 2, 'Utang JK Panjang',              'liabilitas', 'credit', true,  'Header'),
('2410', '2400', 3, 'KTA / Pinjaman Bank',           'liabilitas', 'credit', false, 'DORMANT'),
('2420', '2400', 3, 'Kredit Kendaraan',              'liabilitas', 'credit', false, 'DORMANT'),
('2430', '2400', 3, 'KPR',                           'liabilitas', 'credit', false, 'DORMANT'),

-- ===== 3000 EKUITAS =====
('3000', NULL,   1, 'EKUITAS',                        'ekuitas', 'credit', true,  'Header kelas'),
('3100', '3000', 2, 'Modal',                          'ekuitas', 'credit', true,  'Header'),
('3110', '3100', 3, 'Saldo Awal / Modal Awal',        'ekuitas', 'credit', false, 'Set oleh /setup wizard'),
('3200', '3000', 2, 'Laba Ditahan',                   'ekuitas', 'credit', true,  'Header'),
('3210', '3200', 3, 'Laba Ditahan Tahun Lalu',        'ekuitas', 'credit', false, 'Diisi closing tahunan'),
('3220', '3200', 3, 'Laba/Rugi Tahun Berjalan',       'ekuitas', 'credit', false, 'Calculated dari L/R'),
('3300', '3000', 2, 'Prive / Distribusi',             'ekuitas', 'debit',  true,  'Header — debit normal'),
('3310', '3300', 3, 'Prive (Pengambilan Pribadi)',    'ekuitas', 'debit',  false, 'Tarik uang untuk non-bisnis'),

-- ===== 4000 PENDAPATAN =====
('4000', NULL,   1, 'PENDAPATAN',                     'pendapatan', 'credit', true,  'Header kelas'),
('4100', '4000', 2, 'Pendapatan Operasional',         'pendapatan', 'credit', true,  'Header'),
('4110', '4100', 3, 'Honor / Upah Proyek',            'pendapatan', 'credit', false, 'Aktif'),
('4120', '4100', 3, 'Gaji Tetap',                     'pendapatan', 'credit', false, 'Aktif'),
('4300', '4000', 2, 'Pendapatan Lain-lain',           'pendapatan', 'credit', true,  'Header'),
('4310', '4300', 3, 'Bunga Tabungan / Deposito',      'pendapatan', 'credit', false, 'Aktif'),
('4320', '4300', 3, 'Dividen Diterima',               'pendapatan', 'credit', false, 'Aktif'),
('4330', '4300', 3, 'Keuntungan Penjualan Aset',      'pendapatan', 'credit', false, 'Aktif'),
('4390', '4300', 3, 'Pendapatan Lain-lain',           'pendapatan', 'credit', false, 'Aktif'),

-- ===== 5000 BEBAN PERSONAL =====
('5000', NULL,   1, 'BEBAN PERSONAL',                 'beban', 'debit', true,  'Header kelas'),
('5100', '5000', 2, 'Beban Konsumsi',                 'beban', 'debit', true,  'Header'),
('5110', '5100', 3, 'Makan Harian',                   'beban', 'debit', false, 'Aktif'),
('5120', '5100', 3, 'Kopi & Minuman',                 'beban', 'debit', false, 'Aktif'),
('5130', '5100', 3, 'Jajan / Snack',                  'beban', 'debit', false, 'Aktif'),
('5200', '5000', 2, 'Beban Transportasi',             'beban', 'debit', true,  'Header'),
('5210', '5200', 3, 'BBM / Bensin',                   'beban', 'debit', false, 'Aktif'),
('5220', '5200', 3, 'Ojek Online',                    'beban', 'debit', false, 'Aktif'),
('5230', '5200', 3, 'Angkutan Umum',                  'beban', 'debit', false, 'Aktif'),
('5240', '5200', 3, 'Parkir & Tol',                   'beban', 'debit', false, 'Aktif'),
('5250', '5200', 3, 'Servis & Perawatan Kendaraan',   'beban', 'debit', false, 'Aktif'),
('5300', '5000', 2, 'Beban Komunikasi',               'beban', 'debit', true,  'Header'),
('5310', '5300', 3, 'Pulsa & Data Internet HP',       'beban', 'debit', false, 'Aktif'),
('5320', '5300', 3, 'Internet Rumah / WiFi',          'beban', 'debit', false, 'Aktif'),
('5400', '5000', 2, 'Beban Kesehatan',                'beban', 'debit', true,  'Header'),
('5410', '5400', 3, 'Obat-obatan',                    'beban', 'debit', false, 'Aktif'),
('5420', '5400', 3, 'Dokter / Klinik / RS',           'beban', 'debit', false, 'Aktif'),
('5430', '5400', 3, 'Vitamin & Suplemen',             'beban', 'debit', false, 'Aktif'),
('5500', '5000', 2, 'Beban Pengembangan Diri',        'beban', 'debit', true,  'Header'),
('5510', '5500', 3, 'Buku & Referensi',               'beban', 'debit', false, 'Aktif'),
('5520', '5500', 3, 'Kursus / Pelatihan',             'beban', 'debit', false, 'Aktif'),
('5530', '5500', 3, 'Langganan Digital (Claude, dll)','beban', 'debit', false, 'Aktif'),
('5540', '5500', 3, 'Alat Kerja & Perlengkapan',      'beban', 'debit', false, 'Aktif'),
('5600', '5000', 2, 'Beban Tempat Tinggal',           'beban', 'debit', true,  'Header'),
('5610', '5600', 3, 'Kos / Kontrakan',                'beban', 'debit', false, 'Aktif'),
('5620', '5600', 3, 'Listrik',                        'beban', 'debit', false, 'Aktif'),
('5630', '5600', 3, 'Air',                            'beban', 'debit', false, 'Aktif'),
('5640', '5600', 3, 'Kebutuhan Rumah Tangga',         'beban', 'debit', false, 'Aktif'),
('5700', '5000', 2, 'Beban Sosial & Keluarga',        'beban', 'debit', true,  'Header'),
('5710', '5700', 3, 'Kiriman ke Keluarga (Ortu/Adik)','beban', 'debit', false, 'Aktif — BUKAN internal transfer!'),
('5720', '5700', 3, 'Zakat / Sedekah / Infaq',        'beban', 'debit', false, 'Aktif'),
('5730', '5700', 3, 'Hadiah & Kado',                  'beban', 'debit', false, 'Aktif'),
('5740', '5700', 3, 'Acara Sosial (Kondangan, dll)',  'beban', 'debit', false, 'Aktif'),
('5800', '5000', 2, 'Beban Finansial',                'beban', 'debit', true,  'Header'),
('5810', '5800', 3, 'Bunga Pinjaman / Cicilan',       'beban', 'debit', false, 'Aktif'),
('5820', '5800', 3, 'Biaya Admin & Transfer Bank',    'beban', 'debit', false, 'Aktif — termasuk fee BI-Fast'),
('5830', '5800', 3, 'Bunga Paylater / SpayLater',     'beban', 'debit', false, 'Aktif'),
('5900', '5000', 2, 'Beban Lain-lain Personal',       'beban', 'debit', true,  'Header'),
('5910', '5900', 3, 'Pakaian & Penampilan',           'beban', 'debit', false, 'Aktif'),
('5920', '5900', 3, 'Rekreasi & Hiburan',             'beban', 'debit', false, 'Aktif'),
('5930', '5900', 3, 'Olahraga (Sepeda, Badminton)',   'beban', 'debit', false, 'Aktif'),
('5990', '5900', 3, 'Beban Tidak Terduga',            'beban', 'debit', false, 'Aktif'),

-- ===== 6000 BEBAN USAHA (DORMANT) =====
('6000', NULL,   1, 'BEBAN USAHA',                    'beban', 'debit', true,  'Header kelas — aktif saat mulai bisnis'),
('6100', '6000', 2, 'HPP',                            'beban', 'debit', true,  'Header'),
('6110', '6100', 3, 'HPP Barang Dagang',              'beban', 'debit', false, 'DORMANT'),
('6200', '6000', 2, 'Beban Gaji & SDM',               'beban', 'debit', true,  'Header'),
('6210', '6200', 3, 'Gaji Karyawan',                  'beban', 'debit', false, 'DORMANT'),
('6220', '6200', 3, 'Tunjangan + BPJS',               'beban', 'debit', false, 'DORMANT'),
('6300', '6000', 2, 'Beban Pemasaran',                'beban', 'debit', true,  'Header'),
('6310', '6300', 3, 'Iklan & Promosi',                'beban', 'debit', false, 'DORMANT'),
('6400', '6000', 2, 'Beban Operasional Usaha',        'beban', 'debit', true,  'Header'),
('6410', '6400', 3, 'Sewa Tempat Usaha',              'beban', 'debit', false, 'DORMANT'),
('6420', '6400', 3, 'Listrik & Internet (Usaha)',     'beban', 'debit', false, 'DORMANT'),
('6500', '6000', 2, 'Beban Penyusutan',               'beban', 'debit', true,  'Header'),
('6510', '6500', 3, 'Penyusutan Kendaraan',           'beban', 'debit', false, 'Aktif saat bisnis'),
('6520', '6500', 3, 'Penyusutan Peralatan',           'beban', 'debit', false, 'Aktif saat bisnis'),
('6700', '6000', 2, 'Beban Lain-lain Usaha',          'beban', 'debit', true,  'Header'),
('6710', '6700', 3, 'Kerugian Penjualan Aset',        'beban', 'debit', false, 'DORMANT'),

-- ===== Catch-all =====
('9999', NULL,   3, 'Beban Tidak Terkategorikan',     'beban', 'debit', false, 'CATCH-ALL — semua yang tidak masuk kategori');
